### PR TITLE
Add pyenv

### PR DESCRIPTION
**Pull request by akinnane**

### CODE REVIEW

**Comment by akinnane** [comment]
See https://github.com/alphagov/centralised-security-logging-service/issues/380

**Comment by akinnane** [comment]
See https://github.com/alphagov/centralised-security-logging-service/pull/386

**Review by gds-ahine — APPROVED** [review]
LGTM

**Review by danjoneslf — COMMENTED** [review]
What does this leave as the default global python/python3? This images is used in a lot of places if the default python version changes.

**Comment by akinnane** [comment]
>What does this leave as the default global python/python3? This images is used in a lot of places if the default python version changes.

The default stays as it was. `pyenv` is only used when manually selected or requested via a `.python-version` file.
Screenshot from 2021-02-11 12-51-15

**Comment by danjoneslf** [comment]
Does that mean the pip version for other things using that default 3.7.5 won't have changed? I'm reasonably sure we've used cryptography elsewhere. Should we use pyenv to install 3.7.5 and set pyenv global?

**Comment by akinnane** [comment]
That's a good idea. I've tested it, it works, and I've committed the change.

Screenshot from 2021-02-11 13-13-07

**Comment by akinnane** [comment]
It works for `venvs` too. 
Screenshot from 2021-02-11 13-20-15

**Pull request merged**
