### PR TITLE
Switch to tfenv to enable multiple tf versions

### LINKED ISSUE #38: Install tfenv and multiple terraform versions to enable running different versions per pipeline^
Similar to what Alex did with pyenv. Means we can take advantage of new TF features without having to migrate everything at once. 

*Before merging we need to change CSLS to add a `tfenv use` into the pipeline jobs*

### PR DESCRIPTION
**Pull request by danjoneslf**
If we merge this we will need to add a `tf use` into the CSLS pipeline

### CODE REVIEW

**Comment by akinnane** [comment]
Can we keep the existing terraform versions as-is and add tfenv ontop of them? That way we don't break any of the existing stuff, and can start migrating everything to tfenv.

**Comment by danjoneslf** [comment]
> Can we keep the existing terraform versions as-is and add tfenv ontop of them? That way we don't break any of the existing stuff, and can start migrating everything to tfenv.

0.12.26 is the tfenv default and I've reinstated the 0.14.7 install.

**Review by detnon — DISMISSED** [review]
Looks good 👍🏻

**Review by gds-ahine — APPROVED** [review]
👍

**Pull request merged**
